config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games, only: [:new, :create, :show, :update]

  root to: "games#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_spot.rb
class BoardSpot < ApplicationRecord
  belongs_to :game_board
  belongs_to :played_piece, class_name: "Piece", foreign_key: "played_piece_id", optional: true

  def css_class_list
    size_class = size + "-space"
    x_pos_class = "x-" + x_pos.to_s
    y_pos_class = "y-" + y_pos.to_s
    color_class = (played_piece.color + "-color") if played_piece

    ("board-space " + size_class + " " + x_pos_class + " " + y_pos_class + " " + color_class.to_s).strip
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
  belongs_to :player_turn, class_name: "Player", foreign_key: :player_turn_id, optional: true
  after_create :init_players
  after_create :init_board
  has_many :pieces, through: :players
  has_one :game_board
  has_many :board_spots, through: :game_board

  NUM_PLAYERS = [2, 3, 4]

  def init_players
    possible_colors = Piece::COLORS.dup
    self.number_players.times do
      player_color = possible_colors.pop
      player = Player.new(color: player_color)
      player.piece_set = PieceSet.new(color: player_color)
      player.save!
      self.players << player
    end
    self.player_turn = self.players.first
    self.save
  end

  def init_board
    update(game_board: GameBoard.create())
  end

  def unplayed_pieces
    pieces.select { |piece| !piece.played? }
  end

  def select_unplayed_piece(piece_color, piece_size)
    unplayed_pieces.select {|piece| piece.color == piece_color && piece.size == piece_size}.sample
  end

  def game_turn_order
    players.map { |player| player.color }
  end

  def player_with(color)
    players.select { |player| player.color == color }.first
  end

  def update_turn
    turn_order = self.game_turn_order
    index = turn_order.index(player_turn.color)
    if index == turn_order.size - 1
      update(player_turn: player_with(turn_order[0]))
    else
      update(player_turn: player_with(turn_order[index + 1]))
    end
  end

  def non_turn_players
    players.select { |player| player != player_turn }
  end

end

app/models/game_board.rb
class GameBoard < ApplicationRecord
  belongs_to :game
  has_many :board_spots
  after_create :init_board

  SIZES = ["lg", "md", "sm"]

  def init_board
    [1, 2, 3].each do |y|
      [1, 2, 3].each do |x|
        SIZES.each do |size|
          board_spots << BoardSpot.create(x_pos: x, y_pos: y, size: size, played: false)
        end
      end
    end
  end

  def spots_at(x, y)
    board_spots.select { |spot| spot.x_pos == x && spot.y_pos == y }.sort_by{ |spot| spot.size }
  end

end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :piece_set
  has_one :board_spot, foreign_key: "played_piece_id"

  COLORS = ["red", "blue", "green", "purple"]
  SIZES = [1, 2, 3]

  def played?
    x_pos && y_pos
  end

  def play(x_pos, y_pos)
    size_translate = { 1 => "sm", 2 => "md", 3 => "lg" }
    self.update(x_pos: x_pos)
    self.update(y_pos: y_pos)
    position = game.board_spots.select {|spot| spot.x_pos == x_pos.to_i && spot.y_pos == y_pos.to_i && spot.size == size_translate[self.size] }.first
    self.update!(board_spot: position)
  end

  def game
    piece_set.player.game
  end

end

app/models/piece_set.rb
class PieceSet < ApplicationRecord
  has_many :pieces
  belongs_to :player, optional: true
  after_create :init_pieces

  def init_pieces
    3.times do
      Piece::SIZES.each do |size|
        self.pieces.build(color: self.color, size: size)
      end
    end
    self.save
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game, optional: true
  has_one :game, foreign_key: :player_turn_id
  has_one :piece_set
  has_many :pieces, through: :piece_set

  def unplayed_pieces
    pieces.select { |piece| !piece.played? }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to game_path(@game.id)
    else
      render :new
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    piece = @game.select_unplayed_piece(piece_move_params[:color], piece_move_params[:size])
    piece.play(piece_move_params[:x_pos], piece_move_params[:y_pos])
    @game.update_turn
    @game.save
    render json: @game
  end

  private
  def game_params
    params.require(:game).permit(:number_players)
  end

  def piece_move_params
    params.require(:move).permit(:color, :x_pos, :y_pos, :size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>Otrio</h1>
<%= form_tag games_path, method: :post do %>
  <%= label_tag "number_players", "How many players?" %>
  <%= select("game", "number_players", Game::NUM_PLAYERS) %>
  <%= submit_tag("Start Game") %>
<% end %>

app/views/games/show.html.erb
<h1>Your Game</h1>
<p>
  <%= link_to "New Game", new_game_path %>
</p>
<p>
  Number of players: <%= @game.number_players %>
</p>

<p>
  <%= @game.player_turn.color.capitalize %>'s turn
</p>

<div class="col-md-6">
  <% 3.times do |y| %>
    <div class="row board-row">
      <% 3.times do |x| %>
        <div class="col-md-4 board-square">
          <% @game.game_board.spots_at(x+1, 3-y).each do |spot| %>
            <div class="<%= spot.css_class_list %>">
            </div>
          <% end %>
        </div>
      <% end %>
    </div class="row">
  <% end %>
</div>

<div class="col-md-6">
  <h4><%= @game.player_turn.color %>'s pieces:</h4>
  <% @game.player_turn.unplayed_pieces.each do |piece| %>
    <div class="game-piece <%= piece.color %>-color size-<%= piece.size %>" draggable="true">
    </div>
  <% end %>
  <% @game.non_turn_players.each do |player| %>
  <h4><%= player.color %>'s pieces:</h4>
    <% player.unplayed_pieces.each do |piece| %>
      <div class="game-piece <%= piece.color %>-color size-<%= piece.size %>">
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Otrio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>